#!/bin/bash

# Install prerequisite modules for ubuntu
sudo apt-get install net-tools vim git tig gcc g++ make ctags cscope byobu nodejs

# Download vim utils
mkdir -p "$HOME/.vim/bundle"
cd "$HOME/.vim/bundle"
git clone https://github.com/VundleVim/Vundle.vim.git
git clone https://github.com/vim-scripts/The-NERD-tree.git
git clone https://github.com/vim-scripts/AutoComplPop.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/wesleyche/SrcExpl.git
git clone https://github.com/vim-scripts/CCTree.git
git clone https://github.com/vim-scripts/OmniCppComplete.git
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/vim-airline/vim-airline.git
git clone https://github.com/vim-airline/vim-airline-themes.git
git clone https://github.com/vim-scripts/Conque-GDB.git
git clone https://github.com/majutsushi/tagbar.git
git clone https://github.com/mileszs/ack.vim.git
git clone https://github.com/tpope/vim-surround.git
git clone https://github.com/vim-syntastic/syntastic.git
git clone https://github.com/ternjs/tern_for_vim.git
git clone https://github.com/sjl/gundo.vim.git
git clone https://github.com/Valloric/YouCompleteMe.git
git clone https://github.com/vim-scripts/gsearch.git
git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/godlygeek/tabular.git
git clone https://github.com/vim-scripts/CycleColor.git
git clone https://github.com/jiangmiao/auto-pairs.git
git clone https://github.com/scrooloose/nerdcommenter.git
git clone https://github.com/moll/vim-node.git
git clone https://github.com/pangloss/vim-javascript.git
git clone https://github.com/jelera/vim-javascript-syntax.git
git clone https://github.com/nathanaelkane/vim-indent-guides.git
git clone https://github.com/myhere/vim-nodejs-complete.git
git clone https://github.com/calincru/qml.vim.git

# Download vim colors
mkdir -p "$HOME/.vim/colors"
cd "$HOME/.vim/colors"
git clone https://github.com/tomasr/molokai.git
git clone https://github.com/altercation/vim-colors-solarized.git
git clone https://github.com/Lokaltog/vim-distinguished.git
git clone https://github.com/morhetz/gruvbox.git

# Setup *.vim for colors
cp -n $(find . -name '*.vim') ./

# Setup Ctrl+S Ctrl+Q
echo -en "\n# alias for vim\nalias v='vim'\n\n# A way to disable CTRL + s from sending XOFF\nstty ixany\nstty ixoff -ixon" >> "$HOME/.bashrc"

# Symbolic link for .vimrc
cd "$HOME"
ln -s "$HOME/vim/.vimrc" "$HOME/.vimrc"
cd vim

# Install scripts(gc, resize)
if [ -d "$HOME/.local/bin" ]; then
  cp ./resize "$HOME/.local/bin/"
  cp ./gc "$HOME/.local/bin/"
else
  mkdir -p "$HOME/.local/bin"
  cp ./resize "$HOME/.local/bin/"
  cp ./gc "$HOME/.local/bin/"
fi

# source local bashrc profile
source ~/.profile
source ~/.bashrc
